### ISSUE TITLE
Question regarding authentication

### ISSUE THREAD

**Issue by petergloor** [zmb3/spotify#10]
Is there any way to do the authentication process completely inside go, without having to use an external browser for the login part? I could not find any working solution so far.

**Comment by zmb3** [comment]
If you want to access private data, you must use either the "Authorization Code" flow, which requires that the user grant permission in a browser.  There's no way around this.

This is actually mentioned in [Spotify's FAQ](https://developer.spotify.com/web-api/authorization-guide/#faq).  The best you can do is follow the flow to get the access token and refresh token once, and then after that you can refresh the token without using the browser.
