### ISSUE TITLE
ReleaseDateTime method only defined for FullAlbum struct

### ISSUE THREAD

**Issue by siku2** [zmb3/spotify#101]
#71, which adds the `ReleaseDate` and `ReleaseDatePrecision` fields to the `SimpleAlbum` struct, was merged ages ago, but `SimpleAlbum` doesn't have the `ReleaseDateTime` method which is defined for the `FullAlbum` struct.

Is it possible to move the `ReleaseDateTime` method to the `SimpleAlbum` instead?
I would gladly open a PR if interested.

Tangentially related: Is there a reason why - especially in case of the Album structs - multiple fields are defined both on the "simple" as well as on the "full" variant even though the simple one is embedded?

**Comment by zmb3** [comment]
I get confused, and I think its because sometimes the Web API docs aren't in line with reality.

According to the [docs](https://developer.spotify.com/documentation/web-api/reference-beta/#object-simplifiedalbumobject) `SimpleAlbum` should not have `ReleaseDatePrecision`.

If we can prove that `ReleaseDateTime` should be moved to `SimpleAlbum` I'm happy to take a PR.
And if you see things that are in the simple variant (and thus) embedded in the full variant I'd love to see a PR to fix those, too!

**Comment by siku2** [comment]
I just checked and it really is weird. 
Right now the simplified album object definitely seems to include the `ReleaseDate` and `ReleaseDatePrecision`.

<details>
<summary>track.album value from a get track request</summary>
<p>

```json
{
  "name": "VIDA",
  "artists": [  ],
  "album_group": "",
  "album_type": "album",
  "id": "5C0YLr4OoRGFDaqdMQmkeH",
  "uri": "spotify:album:5C0YLr4OoRGFDaqdMQmkeH",
  "available_markets": [  ],
  "href": "https://api.spotify.com/v1/albums/5C0YLr4OoRGFDaqdMQmkeH",
  "images": [  ],
  "external_urls": {
    "spotify": "https://open.spotify.com/album/5C0YLr4OoRGFDaqdMQmkeH"
  },
  "release_date": "2019-02-01",
  "release_date_precision": "day"
}
```

</p>
</details>

What I find interesting is that these keys are documented in the 
["Old" Reference](https://developer.spotify.com/documentation/web-api/reference/object-model/#album-object-simplified) docs but in the [Beta Reference](https://developer.spotify.com/documentation/web-api/reference-beta/#object-simplifiedalbumobject), the one you linked, they're gone.
Maybe this means they're deprecated, or they simply forgot to include them in the new docs. They're still in "beta" after all.

I also spent some time looking for related issues over at https://github.com/spotify/web-api but I couldn't find any.
