### ISSUE TITLE
Proper way to mock `Client`

### ISSUE THREAD

**Issue by seiyab** [zmb3/spotify#133]
How to test apps that uses this wrapper?
I'm happy if documents exist or an official interface and mock implementations are provided.
Now I define my own interface and inject mock like following.
```go
// example

type SpotifyClient interface {
  GetTracks(ids ...spotify.ID) ([]*spotify.FullTrack, error)
  ...
}

// in test code
type mockSpotifyClient struct {}

func (c *mockSpotifyClient) GetTracks(ids ...spotify.ID) ([]*spotify.FullTrack, error) {
  ...
}
```

**Comment by strideynet** [comment]
Defining your own interfaces is the go way. This is not a concern of the library.
