### ISSUE TITLE
Unsure How To Provide spotify.ID to GetPlaylistTracks()

### ISSUE THREAD

**Issue by cofonseca** [zmb3/spotify#139]
Sorry for posting this here - this isn't really a bug, just more of a question. I'm fairly new to Go and am working with this library for the first time (it seems great, btw!), and I want to simply return all of the tracks in a playlist. I've successfully created a client with my OAuth info - no issues there.

I'm trying to run `client.GetPlaylistTracks()`, which takes in a playlist ID of type `spotify.ID`, which seems to be a string under the hood, but I can't seem to figure out how to create a `spotify.ID`, and `GetPlaylistTracks()` won't accept a simple string. 

The only example I could find was the test for `GetPlaylistOpt()`, which looks like it just takes in a string, so I'm not sure why that doesn't work for me. Could someone please provide (or point me to) an example of how to create a `spotify.ID` object to be used by `GetPlaylistTracks()`?

Thanks in advance!

**Comment by zmb3** [comment]
spotify.ID(“foo”) should do the trick 🙂

**Comment by cofonseca** [comment]
@zmb3 oh boy, not sure how I didn't realize that sooner... thank you very much! That worked beautifully. :)
