### ISSUE TITLE
GetEpisode/GetEpisodes APIs?

### ISSUE THREAD

**Issue by AttilaTheFun** [zmb3/spotify#140]
I saw there were some structures defined for podcast episodes, but the APIs to fetch episodes by IDs don't seem to be implemented here. The APIs are documented here: https://developer.spotify.com/console/get-several-episodes/
Is this something on your roadmap? If not I'd be happy to make a PR to add these APIs. I figure it would be pretty simple to copy the artist / album fetching functions.

**Comment by zmb3** [comment]
Would love a PR! Thanks

**Comment by AttilaTheFun** [comment]
Cool thanks! I probably won't have time this week, but I put it on my todo list and will try to get to it next week. 😃

**Comment by MohitVachhani** [comment]
This is the same thing right: https://github.com/zmb3/spotify/pull/157 ?

**Comment by strideynet** [comment]
That appears to be correct @MohitVachhani
