### ISSUE TITLE
Respect proper handling of context.Context

### ISSUE THREAD

**Issue by strideynet** [zmb3/spotify#143]
Whilst this would require a severely breaking API change, a case can be made for a v2 release that allows the user to provide a context as the first argument of requests. This allows cancellations to propagate correctly.

**Comment by zmb3** [comment]
Yep! This package predates the context package, but I would welcome a PR to do just what you describe. It would provide the opportunity to fix some other things too given a new major version. 

I don’t personally have a need or desire to undertake this, but if somebody wanted to do the work I’d love to see it and would be happy to help.

**Comment by strideynet** [comment]
@zmb3, I've seen a few of the tickets and have an idea of what other things to include in a breaking release.

One thing that did occur to me is that if you are wanting to step away from this project, is that potentially my fork could proceed as v2 once it is complete and that this repository could be marked as deprecated.
