### ISSUE TITLE
Wrong tag name for v1.1.1

### ISSUE THREAD

**Issue by aprosvetova** [zmb3/spotify#152]
It's impossible to install v1.1.1, because of the tag name.

The tag is named `V1.1.1`, starting with the capital `V`, which should be lowercase as for `go mod` specs.
The proper tag name is `v1.1.1`.

The latest installable version as of not is `v1.1.0`.

**Comment by strideynet** [comment]
@aprosvetova , 🤦  thanks for catching that one.

**Comment by strideynet** [comment]
https://github.com/zmb3/spotify/tree/v1.1.1
