### ISSUE TITLE
bug: PlaybackOffset with Position=0 doesn't work

### ISSUE THREAD

**Issue by insomnimus** [zmb3/spotify#161]
First I want to thank the maintainers of this package for their awesome work.

I've stumbled on this issue while working with my spotify shell, [libman](https://github.com/insomnimus/libman).

The snippet below does not work:

```go
client.PlayOpt(&spotify.PlayOptions{
  PlaybackContext: &someURI,
    PlaybackOffset: &spotify.PlaybackOffset{ Position: 0 },
    })
```

It says in the documentation that the position is 0 based, but since the field has `omitempty`, it will omit the field essentiall sending a bare PlaybackOffset.

Here's what spotify returns:

`error: At least one of "uri" or "position" should be specified`

_Edit: Fix md syntax._

**Comment by strideynet** [comment]
Thanks for raising this. I'll try and take a look at this later.

**Comment by omerhanci** [comment]
I guess this fix broke the usage of URI in PlaybackOffset. 

Following code returns: ` Illegal offset: should be position XOR uri`

```
opts.PlaybackOffset = &spotify.PlaybackOffset{
			URI: songUri,
		}
```

**Comment by omerhanci** [comment]
Hi, I created a PR to fix this problem, can you check it? 
https://github.com/zmb3/spotify/pull/177
