### ISSUE TITLE
Anonymous access

### ISSUE THREAD

**Issue by 89z** [zmb3/spotify#162]
You can make a request like this:

~~~
GET /playlist/6rZ28nCpmG5Wo1Ik64EoDm HTTP/1.1
Host: open.spotify.com
User-Agent: Firefox/60
~~~

and in part of the HTML response, you get this:

~~~json
{"clientId":"0971d",
"accessToken":"BQDLN9hyIJn0zvspT1OOHdJBQh7pJVrA1CMBMsuu3jOFDT6o37ti_pH8__M84opDUd0yqkzKxLIfjv9XmAw",
"accessTokenExpirationTimestampMs":1628533452806,"isAnonymous":true,
"recaptchaWebPlayerFraudSiteKey":"6LfCVLAUAAAAALFwwRnnCJ12DalriUGbj8FW_J39",
"app_name":"web_player_prototype","market":"US","locale":{"locale":"en","rtl":false,
"textDirection":"ltr"},"gtmId":"GTM-PZHN3VD","optimizeId":"GTM-W53X654","userCountry":null,
"isPremium":false,"correlationId":"f46dc1f60dc9e932d574104732a0173d",
"retargetingPixels":{"twitter":"o46zp","pinterest":"2617608197512",
"snapchat":"fff7f198-e6aa-4833-b900-92d3854473b2"}}
~~~

`accessToken` can then be used in a request like this:

~~~
GET /v1/playlists/6rZ28nCpmG5Wo1Ik64EoDm HTTP/1.1
Host: api.spotify.com
Authorization: Bearer BQDLN9hyIJn0zvspT1OOHdJBQh7pJVrA1CMBMsuu3jOFDT6o37ti_pH8__M84opDUd0yqkzKxLIfjv9XmAw
~~~

**Comment by strideynet** [comment]
Is this a feature request ?

**Comment by 89z** [comment]
> Is this a feature request ?

@strideynet thats a disappointing comment. Either you dont care about what ive posted, or you dont understand it. If the former, then you can go ahead and close the issue. If the latter, then I am sorry for you.

**Comment by strideynet** [comment]
I do care for feature requests, but it is helpful to gauge exactly what the user is expecting so that the feature can be created to meet their needs. To do that, I need to know what uses the develop is intending to get from the feature. What does it solve that cannot already be done by the library etc, and how would they intend to consume the feature?

If you are willing to provide a bit more detail, I can consider this feature request. 

Is the intention to provide some functionality that automatically makes a first request, and then stores the token to use for future requests? Or is it just to add a feature so that the user can provide a bearer token to the library.

Finally, I am certainly hurt by your jump to attack me personally, on a project I maintain mostly out of good will. I wish that in future you consider your wording more carefully.

**Comment by 89z** [comment]
@strideynet youve yet to show that you even understand what the purpose/benefit of the posted issue is. So until that happens, I dont think I should converse further with you.

**Comment by strideynet** [comment]
It would please me if you would enlighten me as to what benefit this feature would bring. As far as I'm aware, this is pretty much the standard way FOSS projects handle feature requests and that there is nothing unusual about me asking you to provide more details.

I would love for this library to be more complete, but unfortunately, I do have a day job so I rely on users of the library to provide useful feedback to me. I don't have time to personally scope out every single potential feature.

I will be more than happy to look into implementing this if you could provide more information about your use case. If there is documentation about this form of authentication available officially anywhere, that would also be appreciated. I'm cautious of adding support for authentication mechanism that isn't officially supported by Spotify.

**Comment by strideynet** [comment]
Unfortunately, having discussed this with others it appears you are well-known for hostile interactions with open-source maintainers, and will be closing this issue.

I would appreciate you no-longer interacting with this repository.

**Comment by 89z** [comment]
> It would please me if you would enlighten me as to what benefit this feature would bring.

My understanding is, that currently this package requires authentication for all requests:

https://github.com/zmb3/spotify#authentication

Some users might want to make anonymous requests, because of privacy or any number of other reasons. The method shown in the original post, allows people to do that.

> I would love for this library to be more complete, but unfortunately, I do have a day job so I rely on users of the library to provide useful feedback to me. I don't have time to personally scope out every single potential feature.

Frankly, I dont care if you implement this or not. I know how to do it, so I can just write my own package with the feature. I posted this mainly as a courtesy, in case a maintainer here was interested in implementing it.

> If there is documentation about this form of authentication available officially anywhere, that would also be appreciated. I'm cautious of adding support for authentication mechanism that isn't officially supported by Spotify.

Most API these days only offically support authenticated access. This is useful for the company providing the API, as they can use the data for their own purposes (analytics etc). However authentication really doesnt do anything for the end user. Its just a pointless burden to getting the information you need for a program you may be writing. Consider the playlist I put in the original post. That playlist is public information. You can browse to the playlist HTML page [1] right now, logged out, and still see the data. So why can you do that with HTML, but not with the API? Well you can, using my method in the original post.

Finally, I just want to kind of hit home on the fact that I dont care what you do with this issue. Ideally you would just read the original post, see the value in it, and implement it, because you realize how valuable a feature it can be. But it seems you either dont understand the potential value of what Ive posted, or you dont care. Thats not an insult, its just honest feedback.

1. https://open.spotify.com/playlist/6rZ28nCpmG5Wo1Ik64EoDm
