### ISSUE TITLE
App engine

### ISSUE THREAD

**Issue by cescoferraro** [zmb3/spotify#17]
app engine seems to need a custom context to work somewhy:

`Post https://accounts.spotify.com/api/token: not an App Engine context`

oauth2.NoContext is user for all Follow, NewClient and Unfollow methods.
Should those accept a golang.net/x/net/context as an argument ?

**Comment by zmb3** [comment]
They should accept a context.Context (from the std lib), not from x/net.

In fact the whole library should be updated to make use of context.

**Comment by cescoferraro** [comment]
@zmb3 still couldnt figure out how to pass a proper context to appengine.
Anyway,  I ll try to code this PR to see what you think

**Comment by zmb3** [comment]
With appengine you would use [`appengine.NewContext(req)`](https://cloud.google.com/appengine/docs/go/reference#NewContext).

We should probably tag the current state of this library as 1.0 and start to work on 2.0 with context support for all functions.  I don't have a lot of spare time to work on this, would love your help :-)

**Comment by cescoferraro** [comment]
@zmb3 tried that without luck. I will be working on that project again this weekend.
I will certally push a PR when I get it to work. The refactor itself should be very straight forward

**Comment by strideynet** [comment]
Closing this ticket as it's now a duplicate of others.
