### ISSUE TITLE
ERR: getaddrinfo failed: -3 spotify

### ISSUE THREAD

**Issue by sirakai-pc** [zmb3/spotify#176]
Spotify's client gui doesn't run if internet is off.
`/proc/self/exe: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)  (spotify:6513): GLib-GIO-CRITICAL **: 00:34:34.543: g_dbus_connection_send_message: assertion 'G_IS_DBUS_CONNECTION (connection)' failed  (spotify:6513): GLib-GIO-CRITICAL **: 00:34:34.544: g_dbus_connection_send_message: assertion 'G_IS_DBUS_CONNECTION (connection)' failed  (spotify:6513): GLib-GIO-CRITICAL **: 00:34:34.675: g_dbus_connection_send_message: assertion 'G_IS_DBUS_CONNECTION (connection)' failed  (spotify:6513): GLib-GIO-CRITICAL **: 00:34:34.724: g_dbus_connection_send_message: assertion 'G_IS_DBUS_CONNECTION (connection)' failed [2021/11/15 00:34:39:6367] ERR: getaddrinfo failed: -3 [2021/11/15 00:34:39:7901] ERR: getaddrinfo failed: -3 [2021/11/15 00:34:40:4292] ERR: getaddrinfo failed: -3`

**Comment by strideynet** [comment]
This isn't Spotify support sadly, maybe try their forums ?
