### ISSUE TITLE
Program hangs when a client method is called within a goroutine?

### ISSUE THREAD

**Issue by amirrezapanahi** [zmb3/spotify#199]
I have these goroutines that run a function called "searchAlbums" for different related artists

relatedArtists = array of related Artists objects
recommended = buffered channel which has a capacity of 6
c = *gin.Context

```go
	for len(recommended) != cap(recommended) {
		go func() {
			recommended, err = searchAlbums(relatedArtists[:len(relatedArtists)*(1/3)], originalColorScheme, recommended, c)
			if err != nil {
	                    //handle error
			}
		}()
		go func() {
			recommended, err = searchAlbums(relatedArtists[len(relatedArtists)*(1/3):len(relatedArtists)*(2/3)], originalColorScheme, recommended, c)
			if err != nil {
	                    //handle error	
			}
		}()
		go func() {
			recommended, err = searchAlbums(relatedArtists[len(relatedArtists)*(2/3):], originalColorScheme, recommended, c)
			if err != nil {
	                    //handle error	
			}
		}()
	}
```

My main issue comes from within the **searchAlbums** function where I invoke the client's **getArtistAlbums** method 

```go
albums, err := client.GetArtistAlbums(spotify.ID(artist.Id))
```

**The program seems to hang once it calls this method and never resolves**

When I call the searchAlbums function in the main thread it runs fine. Any idea why this is happening once I start introducing concurrency? Bare in mind I'm still a beginner with concurrency and go, so any insight will be helpful.

**Comment by strideynet** [comment]
This feels like potentially an issue with your concurrency implementation, rather than our library.

I highly recommend seeking help on the Gopher's slack. I'm usually around on there as well, so I may be able to give a better hand there.
