### ISSUE TITLE
Refreshing token with Client Credentials Flow

### ISSUE THREAD

**Issue by code-qote** [zmb3/spotify#201]
Hello. How can I refresh token with Client Credentials Flow?
Here is my code:
```
config := &clientcredentials.Config{
    ClientID:     clientID,
    ClientSecret: clientSecret,
    TokenURL:     spotifyauth.TokenURL,
}
token, err := config.Token(s.ctx)
token.RefreshToken = refreshToken

if err != nil {
    log.Fatal("FATA: SpotifyEngine:" + err.Error())
}

httpClient := spotifyauth.New().Client(s.ctx, token)
s.client = spotify.New(httpClient)
```

**Comment by strideynet** [comment]
Why would you use a refresh token with a Client Credentials flow ? You have all the information necessary to generate a new token at will.

**Comment by code-qote** [comment]
Should I use `token, err := config.Token(s.ctx)` to generate a new one?

**Comment by strideynet** [comment]
yes.

**Comment by code-qote** [comment]
Thank you very much!

**Comment by schicho** [comment]
I am unsure on what the solution here is. Could you please elaborate?

Some issues mention the token would automatically update, this says I have to do it manually.

Right now I have the following error:
`oauth2: token expired and refresh token is not set`

I create my client with the example code provided

```go
        config := clientcredentials.Config{
		ClientID:     ClientID,
		ClientSecret: ClientSecret,
		TokenURL:     spotifyauth.TokenURL,
	}

	token, err := config.Token(context.Background())
	if err != nil {
		return nil, err
	}
	httpClient := spotifyauth.New().Client(context.Background(), token)
	client := spotify.New(httpClient)
```

Am I missing something or what is the best practice to update the token?

**Comment by code-qote** [comment]
I just create a new token and new Spotify client every 30m. It makes it not to expire. 
Something like this

```
func newToken() {
	token, _ := s.config.Token(s.ctx)

	if err != nil {
		return
	}
	token.RefreshToken = refreshToken
	httpClient := spotifyauth.New().Client(ctx, token)
	client = spotify.New(httpClient)
}
```
