### ISSUE TITLE
How to save tracks to current user (aka liked songs)

### ISSUE THREAD

**Issue by tetafro** [zmb3/spotify#226]
I want to set "like" for a track ([API docs for this](https://developer.spotify.com/documentation/web-api/reference/save-tracks-user)). As I can see, it is not implemented right now. Is there any workaround?

**Comment by subash774** [comment]
[this](https://github.com/zmb3/spotify/blob/master/library.go#L42) is probably what you're looking for?

**Comment by strideynet** [comment]
@subash774 is correct

**Comment by awsms** [comment]
Sorry to hijack this old issue, but which function lets you see the actual library's content?

**Comment by subash774** [comment]
> Sorry to hijack this old issue, but which function lets you see the actual library's content?

@awsms don't think there's a function to list all but if you create an issue, someone can pick it up? (idm picking it up if @strideynet is cool with adding that)

**Comment by strideynet** [comment]
No objection to someone raising an issue and patch to add methods for the Get User's Saved Albums / Tracks endpoints

**Comment by subash774** [comment]
@awsms while I was [preparing the PR](https://github.com/subash774/spotify/pull/1) to add getting list of tracks saved by the user, I realised, it's already been implemented [here](https://github.com/zmb3/spotify/blob/master/user.go#L123) 😅 

@strideynet worth adding "symlink" way of getting it from the library module too? By symlink, I mean using the function from `user.go` exposing it from `library.go`? Not sure if that's worth it though, could be a code smell
