### ISSUE TITLE
I keep getting "Missing required parameter: client_id" on authentication example

### ISSUE THREAD

**Issue by percit** [zmb3/spotify#230]
Hi, so I am trying to get authentication example to work, but I keep getting "Missing required parameter: client_id". After manualy pasting my client ID from Spotify I just get "This site can’t be reachedlocalhost refused to connect.". My spotify redirectUri is set correctly, so I am not sure what to do more. Can anybody help me?

**Comment by TimHi** [comment]
I'm assuming you are trying to run _authenticate.go_. 
Are you sure the redirect url is set up correctly?

You need to register _http://localhost:8080/callback_ as mentioned [here](https://github.com/zmb3/spotify/blob/master/examples/authenticate/authcode/authenticate.go#L4).
Also the missing client id is probably due to you not having the enviroment variable set as mentioned in the comment aswell.

**Comment by percit** [comment]
yeah, I do have redirect URI, and added client_id and client secret, like this:
    auth := spotifyauth.New(
        spotifyauth.WithClientID(SpotifyClientID),
		spotifyauth.WithClientSecret(SpotifyClientSecret),
        spotifyauth.WithRedirectURL(redirectURI),
        spotifyauth.WithScopes(
            spotifyauth.ScopePlaylistModifyPublic,
            spotifyauth.ScopePlaylistModifyPrivate,
        ),
    )
and it parses client_id correctly now, but in URI that I got from app, I cannot find client secret, and I get "404 page not found"

**Comment by TimHi** [comment]
It's normal that the client secret is not part of the URL. That exchange will happen when the tokes are requested, see [docs](https://developer.spotify.com/documentation/web-api/tutorials/code-flow).

The redirectURI from spotifyauth.WithRedirectURL(redirectURI) is registered in your [spotify app](https://developer.spotify.com/dashboard)?
From the authcode example it should look like this:
![image](https://github.com/zmb3/spotify/assets/10931525/bc0da1f6-2b94-4f28-83ae-8c6483c8ccaf)


If that is setup correctly the example should run just fine. Maybe you have external tools (firewall, proxy ..) that block the access of your localhost

**Comment by percit** [comment]
![image](https://github.com/zmb3/spotify/assets/55813873/5b28f05f-0b8f-4e90-9abf-0e96d4f750f7)
 yes, I have uri. And no, I don't have any problem with localhost, as I used it many times before in previous golang projects. Is there a chance that golang spotify api has a bug? Have you tried using this authenticate.go recently?

**Comment by percit** [comment]
I managed to make it work on bare example, but not on my code. Could you take a quick look if you have time? https://github.com/percit/Yt2Spotify/blob/work-branch/main.go
