### ISSUE TITLE
unmarshal fail.  【curl --request GET \   --url https://api.spotify.com/v1/artists/0TnOYISbd1XYRBk9myaseg】

### ISSUE THREAD

**Issue by kristopher8** [zmb3/spotify#243]
json: cannot unmarshal number 1.1113535E7 into Go struct field Followers.followers.total of type uint

**Comment by leonid-ed** [comment]
Hi @kristopher8 , looks like this is an issue on Spotify side. 

I've created [a ticket there](https://community.spotify.com/t5/Spotify-for-Developers/Get-Artist-API-endpoint-responds-with-result-in-inconsistent/td-p/5806916) – would be great if you also add your comment there to make it more visible for the Spotify team.

**Comment by leonid-ed** [comment]
@tmstn I've applied your fix in my fork and it worked! Thanks a lot!

**Comment by wernerdweight** [comment]
I created a PR with the changes from @tmstn.

**Comment by wernerdweight** [comment]
The float numbers are now actually also in other fields on track structs (`SimpleTrack`, `FullTrack`, at least). A custom numeric type would probably be a better solution than custom unmarshaling in this PR. 🤔

**Comment by strideynet** [comment]
Thanks folks - apologies for not commenting on this. I've been keeping an eye on it and was hoping Spotify would address this, but in typical Spotify fashion, it looks like we won't be seeing a fix on their side.
