### ISSUE TITLE
Availability of refreshToken() Function in Released Version

### ISSUE THREAD

**Issue by grantsanders** [zmb3/spotify#247]
I've noticed that the Authenticator function `refreshToken()`, which was merged into the master branch in PR #233, is not present in the source code of the most recent version of the package (v2.4.0). While users can certainly specify version in go.mod, it's a bit confusing to have features merged three months ago not be present in the ```go get``` package itself.

I've been writing a small script to automate playlist creation on a monthly basis, and the only reason I ran into the issue was because of my need for rolling authentication (without me having to sign in over and over again).

Thanks for your work on the package itself! I'm using a version built off of the master branch and it's fast and easy to use.

**Comment by strideynet** [comment]
Oops, looks like I forgot to cut a release - https://github.com/zmb3/spotify/releases/tag/v2.4.1

**Comment by grantsanders** [comment]
Thanks!
