### ISSUE TITLE
Transfer Playback Multiple IDs

### ISSUE THREAD

**Issue by lukehobbs** [zmb3/spotify#30]
I might just be missing something, but why should TransferPlayback take a slice of deviceIDs rather than just a single ID to transfer playback to?

```
func (c *Client) TransferPlayback(deviceIDs []ID, play bool) error {
```

I am still trying to figure out what is causing it, but the TransferPlayback method is very finicky for me and seems to only work when I run it in between a song change or if I start the playback through the app and not the API.

Edit: It seems like I can transfer the playback between devices but the playback gets stuck on my desktop PC running Windows 10 and then I'm unable to transfer playback from this device. This might be just an issue with my desktop client... If so I can close this if the slice of deviceIDs is purposeful.

**Comment by zmb3** [comment]
You're not missing anything.  `TransferPlayback` was just added in a recent PR and I didn't catch this when I reviewed it.  This should definitely take a single device ID, and since it's so new I'm fine with changing the API to fix it.

Interested in submitting a PR for this?

**Comment by lukehobbs** [comment]
Sure, I should have some time today to hack away at it.
