### ISSUE TITLE
Adding Client credentials as authorisation option

### ISSUE THREAD

**Issue by adonnelly** [zmb3/spotify#37]
I am trying to use your extremely useful package for a report I am writing, However the report is run as a daily job and must connect using client credentials https://developer.spotify.com/web-api/authorization-guide/#client-credentials-flow.  Currently you support Authorization flow.  Just wondering if its possible to use Client Credentials with your package. Using the oauth2/clientcredentials package it seems straight forward to create an authorised client. But I cannot assign it to a spotify client. Any suggestions. 

```
import (
	"context"
	"fmt"
	"github.com/zmb3/spotify"
	"golang.org/x/oauth2/clientcredentials"
)

func main() {
		config := &clientcredentials.Config{
			ClientID:     "CLIENTID",
			ClientSecret: "SECRET",
			TokenURL:     "https://accounts.spotify.com/api/token",
	}
	//Creates an authorized *http.client
	AuthorizedClient := config.Client(context.Background())
	// need to assign authorizedClient to spotify.client

```

**Comment by adonnelly** [comment]
The following seems to work. However I am not sure what happens when token expires. 
`	config := &clientcredentials.Config{
			ClientID:     "CLIENTID",
			ClientSecret: "SECRET",
			TokenURL:     "https://accounts.spotify.com/api/token",
	}
	token, err := config.Token(context.Background())
	if err != nil {
		log.Println(err)
		return
	}
	var auth spotify.Authenticator
	spotifyClient := auth.NewClient(token)

`

**Comment by chances** [comment]
@adonnelly From skimming the oauth2 client credentials package, when a token expires the oauth2 Client  accessing the token should request a new token with the `oauth2/clientcredentials` `TokenSource`. It seems to work as described in my application.

**Comment by klausenbusk** [comment]
> @adonnelly From skimming the oauth2 client credentials package, when a token expires the oauth2 Client accessing the token should request a new token with the oauth2/clientcredentials TokenSource. It seems to work as described in my application.

Do you have some code you want to share?
