### ISSUE TITLE
Client returns 'spotify: HTTP 204: No Content ' as an error

### ISSUE THREAD

**Issue by vansante** [zmb3/spotify#45]
Up until recently it worked fine, but now some calls return the following error:

spotify: HTTP 204: No Content (body empty)

Which is not really an error if you ask me ;)

Ive identified at least these functions to do this:
```
p.client.PlayOpt(&spotify.PlayOptions{
	URIs: []spotify.URI{URI},
})
```

```
p.client.Repeat("off")
```

```
p.client.Shuffle(false)
```

But there might be more?

**Comment by zmb3** [comment]
Thanks for the report. You're right it's not an error. I didn't scrutinize
the recent pull request as closely as I should have. Will get this fixed
asap!
