### ISSUE TITLE
Token error

### ISSUE THREAD

**Issue by latargere** [zmb3/spotify#53]
Hi,

I'm playing with the player example but I have some issue sending request just after I logging or sending 2 commands
The error I got is sometimes 
```
2017/10/07 12:18:21 oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Authorization code expired"}
```

or

`2017/10/07 12:21:51 oauth2: cannot fetch token: 400 Bad Request
Response: {"error":"invalid_grant","error_description":"Invalid authorization code"}`

Is there an issue with oauth2 lib ?

**Comment by leonid-ed** [comment]
Hi latargere,

I faced a similar issue. It looks like you should change your approach to reusing a user's token.
Please refer to #137 to find out how to use already existing token in an example there.
It really helped me.

**Comment by strideynet** [comment]
I'm going to go ahead and close this as stale. If this re-occurs, please open a new ticket.
