### ISSUE TITLE
Help on how to use scopes

### ISSUE THREAD

**Issue by falzm** [zmb3/spotify#55]
Hello

I'm having trouble using your package to access Spotify web API, looking to retrieve [recently played items](https://developer.spotify.com/web-api/web-api-personalization-endpoints/get-recently-played/):

```golang
package main

import (
	"context"
	"fmt"
	"log"

	"github.com/zmb3/spotify"
	"golang.org/x/oauth2/clientcredentials"
)

func main() {
	config := &clientcredentials.Config{
		ClientID:     "...",
		ClientSecret: "...",
		TokenURL:     spotify.TokenURL,
		Scopes:       []string{spotify.ScopeUserReadRecentlyPlayed},
	}

	token, err := config.Token(context.Background())
	if err != nil {
		log.Fatalf("unable to get token: %v", err)
	}

	client := spotify.Authenticator{}.NewClient(token)

	recent, err := client.PlayerRecentlyPlayedOpt(&spotify.RecentlyPlayedOptions{Limit: 10})
	if err != nil {
		log.Fatalf("unable to get recently played items: %v", err)
	}

	for _, item := range recent {
		fmt.Println(item)
	}
}
```

When I execute this code the API call for recently played items fails: `2017/10/29 15:26:53 unable to get recently played items: Insufficient client scope`

Did I miss something regarding the specification of scopes?

**Comment by zmb3** [comment]
Hmm.  That's exactly what I would have tried.  I tried this in the [console](https://developer.spotify.com/web-api/console/get-recently-played/) and it worked as expected.

Will have to look into this one some more.

**Comment by bundyfx** [comment]
Also get the same error with this one. revive bump 🎉

**Comment by zmb3** [comment]
The client credentials grant type cannot be used to access user information.
