### ISSUE TITLE
TransferPlayback doesn't work as intended.

### ISSUE THREAD

**Issue by marante** [zmb3/spotify#59]
Hi. I have recently tried to use TransferPlayback method without success. Whenever I run the code below, the change of track in the PlayOpt method works, but it does not switch playback device. I start Spotify on my phone and begin playing music. I run the code, and song switches, but it doesn't change playback device to my computer. Do I have to do something else or am I just missing something?

```golang
devices, err := client.PlayerDevices()
	if err != nil {
		log.Print("L72: ", err)
	}

	for _, device := range devices {
		if device.Name == "VictorsMacbookAir" {
			fmt.Println(device.ID)
			err = client.TransferPlayback(device.ID, true)
			if err != nil {
				log.Print("L79: ", err)
			}
			w.Header().Set("Content-Type", "text/plain")
			fmt.Fprintf(w, "Login completed, transfering playback to: %s", device.Name)
			break
		}
	}

	songs := []spotify.URI{"spotify:track:7BfiAzV3ASEK9egnfxN1v1"}
	options := &spotify.PlayOptions{
		URIs: songs,
	}
	err = client.PlayOpt(options)
	if err != nil {
		log.Print("L93: ", err)
	}
```

Best regards,
Victor

**Comment by zmb3** [comment]
I don't see anything obviously wrong here.  Perhaps a stupid question, but can you verify that `TransferPlayback` is returning a `nil` error?  If you call `client.PlayerState()` after changing the state do you see the active device change?  What if you sleep a little bit before trying to change the track - does that result in different behavior?

**Comment by marante** [comment]
Hi, thanks for the answer! I can confirm that the error is infact a nil one, nothing wrong there. If I print out currently active device, I see that it's my computer. However, the music still plays from my phone.

I dug around some more, and changed some things; I can get it to work about 50% of the times, sometimes the music starts playing on the computer for about 0.5 seconds, and then goes back to the phone. I do suspect this has something to do with Spotifys API, rather then your code. I think I'll resort to asking on the spotify github instead, as I don't think your code is faulty.

If you have no more further questions or thoughts, you can close this issue if you'd like! Thanks for the response!
