### ISSUE TITLE
Bad Gateway?

### ISSUE THREAD

**Issue by rphillips** [zmb3/spotify#63]
When I am executing my app I am receiving a Bad Gateway on a regular basis, but not on every run. The app is simply searching for tracks and manipulating playlists. Has anyone else seen this before? Retries are turned on within the API client.

**Comment by zmb3** [comment]
Bad gateway sounds like a server-side error.  May be worth filing an issue at https://github.com/spotify/web-api/issues

**Comment by rphillips** [comment]
Looks like there is a bug upstream (https://github.com/spotify/web-api/issues/541). Thanks for the pointer to the upstream project.
