### ISSUE TITLE
Oauth Credential Storage

### ISSUE THREAD

**Issue by rphillips** [zmb3/spotify#64]
Is there a way to save the oauth credentials to the filesystem, so they can be used on a subsequent run?

**Comment by falzm** [comment]
Good question, I was actually about to ask a similar one...

I'm trying to save the `code` returned from the Spotify callback request and provide it to the [Exchange()](https://godoc.org/github.com/zmb3/spotify#Authenticator.Exchange) method, but it doesn't seem to work: I get a `400 Bad Request ({"error":"invalid_grant","error_description":"Invalid authorization code"})` 😞

**Comment by zmb3** [comment]
Don’t save the code, save the token. You can get the token via the clients Token() method. 

See #26
