### ISSUE TITLE
Login exits with HTTP 204 after sometime between 21:00 and 21:30 CEST and works again after ~11:35

### ISSUE THREAD

**Issue by jess-sch** [zmb3/spotify#70]
After clicking the auth link....
`2018/07/13 21:50:48 spotify: HTTP 204: No Content (body empty)`
(exit code 1)

Happened yesterday and today, starting from something between 21:00 and 21:30 Central European Standard Time. Will keep trying to log in in order to find out when it starts working again.

**Comment by lumi-sch** [comment]
(I'm using `examples/player` for testing this)

**Comment by zmb3** [comment]
This happens from time to time.  We are probably expecting a `200 OK` and instead got a `204 no content`.  In some cases Spotify's docs say they always return a specific status code, and we try to follow that.

If you can find out which call specifically is failing with this error that will help.  In any case, we probably need to relax the logic such that any `2XX` status is a non-error.

**Comment by lumi-sch** [comment]
Works again since 11:39 AM... just started debugging and now it's working again

**Comment by strideynet** [comment]
I'm going to go ahead and close this issue as it's relatively old. Feel free to re-open if it's still a problem.
