### ISSUE TITLE
PlayerCurrentlyPlaying returns err io.EOF when not playing

### ISSUE THREAD

**Issue by diamondo25** [zmb3/spotify#72]
Sometimes, when there's no player registered (I suppose), the API returns an EOF. The token _is_ correct and the error can be ignored.

```golang
	if ftl, err := client.PlayerCurrentlyPlaying(); err != nil {
		if err != io.EOF {
			log.Fatal(err)
		}
	} else {
		if !ftl.Playing {
			log.Println("Currently not playing...")
			return
		}
		// Do whatever
	}
```

**Comment by zmb3** [comment]
Thanks for pointing this out.  I don't see any action necessary here, so I'll close the issue.

**Comment by chrisvdg** [comment]
@zmb3, should this not at least be documented? 
We could also make it return a self defined error for this that's more readable (to compare with.)

**Comment by chrisvdg** [comment]
The API returns a 204 for this request without body, so we can check for that response code and return a `ErrNoPlayerCurrentlyPlaying` or something.

**Comment by zmb3** [comment]
Should be able to just update `spotify/Client.execute()` to skip reading the response body in the event of a 204.

Something like this, for example:
```
		if result != nil  && resp.Status != http.StatusNoContent {
			if err := json.NewDecoder(resp.Body).Decode(result); err != nil {
				return err
			}
		}
```
