### ISSUE TITLE
Full examples needed

### ISSUE THREAD

**Issue by bruceadowns** [zmb3/spotify#8]
I could be helpful for newbies and to help in adoption to have working examples to match https://github.com/zmb3/spotify#api-examples.

Also, similar to those found here:
https://github.com/op/go-libspotify/tree/master/examples

**Comment by bruceadowns** [comment]
I wrote a couple of samples using your library, and would be willing to write more cli examples.

Let me know if you have any recommendations for what you would like to see.

**Comment by zmb3** [comment]
I completely agree this is a great idea.  I'd be happy to put together a few examples or work with you on what you've started.  What have you come up with so far?

**Comment by bruceadowns** [comment]
I was thinking of:
\examples\search\search.go
\examples\users\users.go
\examples\tracks\tracks.go
\examples\playlist\playlist.go

And maybe a shell:
\spotsh.go

Modeled after the previously noted libspotify gospshell.

**Comment by bruceadowns** [comment]
I created a simple PR that basically took your readme example. It's not terribly interesting as is, but 1) it demonstrates it simply, and 2) could be filled in to accept input flags to match the capabilities.

**Comment by zmb3** [comment]
Looks good. I'll merge it today and add a few more examples.

As for the shell, I actually have a project similar to that. I'll clean it up and either add it to this repo or open source it and reference it in the readme.
