### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by Kevintjeb** [zmb3/spotify#85]
Hello,

While trying to receive a token, to make subsequent requests, I get the following error :

`2019/01/13 18:33:09 couldn't get token: Post https://accounts.spotify.com/api/token: x509: certificate signed by unknown authority`

This of course implies that the certificate, that is offered, is signed by a (to my computer) unknown authority. 
However, this did work sometime in November last year. So spotify changed something up I'm guessing.

Would you have an Idea how to get this working, besides authorizing the certificate?

The following code was used:
```
config := &clientcredentials.Config{
	ClientID:     os.Getenv("SPOTIFY_ID"),
	ClientSecret: os.Getenv("SPOTIFY_SECRET"),
	TokenURL:     spotify.TokenURL,
}
token, err := config.Token(context.Background())
if err != nil {
	log.Fatalf("couldn't get token: %v", err)
}

client := spotify.Authenticator{}.NewClient(token)
```

**Comment by zmb3** [comment]
This is likely something with your environment. Are you running on a corporate or hotel network by chance?  Is your OS up to date?

**Comment by Kevintjeb** [comment]
Hmm. 

I am not running on a corporate or hotel network, I am using the latest gen, almost fully specced macbook pro with the latest Macos Mojave version.

Also verified by using a hotspot on my phone, that shares my LTE connection.

**Comment by Kevintjeb** [comment]
Issue was related to Docker.

For further users:

Creating a docker container, using multistage builds, without copying CA certs. It will be missing certs!
