### ISSUE TITLE
Using spotifyd

### ISSUE THREAD

**Issue by Eun** [zmb3/spotify#99]
Hello there!
First of great work and thanks for making this package! :+1: :heart: 

I am trying this package to control [spotifyd](https://github.com/Spotifyd/spotifyd), however, somehow spotify API always returns with `HTTP 202: Accepted (body empty)` instead of `HTTP 204: No Content` as soon as I make a call (selected spotifyd as connected device).
The commands get trough! And spotifyd does everything fine, but `HTTP 202` is not expected in this package so it will aways return an error.

I know that there is an Autoretry mode, however spotify always returns 202 no matter what, so I end up in an endless loop...

My guess is that there is an issue on spotifyd's side. (Will create a ticket there as well)
However I think there should be an option to enable `HTTP 202 is good enough` mode

What do you think?
BTW: willing to implement that feature!

**Comment by zmb3** [comment]
> However I think there should be an option to enable HTTP 202 is good enough mode

I would agree, and go so far to say that the default mode should be HTTP 2XX is good enough mode.

**Comment by Eun** [comment]
👍 will implement
